version: "3.9"
services:
  web:
    container_name: ${PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/Dev.Dockerfile
    env_file: ../.env
    volumes:
    - ..:/usr/src/app
    - venvs:/venvs  # mount a venvs volume to avoid clashes with .venv in local dev
    - app_volume:/usr/src/circleci
    ports:
    - "5678:5678"

volumes:
  app_volume:
  venvs:
